# Generated by Django 5.1.1 on 2024-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
