# Generated by Django 5.1.1 on 2024-09-08 10:28

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(core.enums.USER_TYPES['REGULAR_USER'], 'Regular User'), (core.enums.USER_TYPES['INSTRUCTOR'], 'Instructor'), (core.enums.USER_TYPES['SUPER_ADMIN'], 'Super Admin')], default=core.enums.USER_TYPES['REGULAR_USER']),
        ),
    ]
